### ISSUE TITLE
New version 

### ISSUE THREAD

**Issue by zmays** [Paxa/kt#3]
When you get a chance can you update this docker image to pull from the latest commit here: https://github.com/fgeller/kt/commit/05fbd0c03dca2aa927ada5365fab18064c162e5c

Some admin stuff was added that looks pretty useful.

Thanks!

**Comment by Paxa** [comment]
Thank for letting know. I've pushed new images

**Comment by tyranron** [comment]
@Paxa would you be so kind to rebuild from latest `master` again? I has some useful improvements.
